version: 2.17.2

services: 

# BACKEND API
  face-rec-api-docker: 
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/face-rec-api-docker
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: face-rec-docker
      POSTGRES_HOST: postgres
    links:
      - postgres
      - redis
    ports: 
      - "3000:3000"
    volumes: 
      - ./:/usr/src/face-rec-api-docker

# POSTGRES
  postgres:
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: face-rec-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"

# REDIS
  redis: 
    image: redis
    ports:
      - "6379:6379"
